### ISSUE TITLE
Possible memoryleak while destroing a context

### ISSUE THREAD

**Issue by Hades0299** [kobalicek/mathpresso#12]
As I am interested in this project, i played around with it a bit. I noticed that while compiling under Windows for x86 that the Context-object is not destroyed, when it is not referenced anymore, while that is with x86_64 it is destroyed correctly. If i call the destructor by hand, under x86 it works as expected, while under x86_64 i get a memory-access-vioation.
I dug a bit deeper and noticed, that the function `mpAtomicDec` has diffrent implementations, depending on the platform:
```c++
# if defined(__x86_64__) || defined(_WIN64) || defined(_M_IA64) || defined(_M_X64)
[...]
//! \internal
static MATHPRESSO_INLINE uintptr_t mpAtomicDec(uintptr_t* atomic) {
  return _InterlockedDecrement64((__int64 volatile *)&atomic);
}
# else
[...]
//! \internal
static MATHPRESSO_INLINE uintptr_t mpAtomicDec(uintptr_t* atomic) {
  return _InterlockedDecrement((long volatile *)atomic);
}
# endif // _64BIT
``` 
(mpatomic_p.h, lines 31+)
I'm confused with the `&atomic` with x86_63 and `atomic` under x86. 

As I am not shure what the intended behaviour is, and as my experience with C++ is limited, i cannot give a direct fix for this.

**Comment by kobalicek** [comment]
Hi, thanks for the report, I see the problem. I will merge this tonight.

**Comment by kobalicek** [comment]
Thanks again, merged with one addition.
