### ISSUE TITLE
adding arrays with 'var' or addConstant

### ISSUE THREAD

**Issue by nelson2005** [kobalicek/mathpresso#3]
I'm working with your latest code, trying to take the 'var' keyword for a test drive.  It's very useful!

I'm curious as to how difficult it would be to add arrays, something like

var a[] = {1, 2, 3, 4};
var index = 0;
a[index];

or, using addConstant, something like addConstant(varname, double* ptr, size_t length), after which varname[index] could be retrieved in jitted code.

**Comment by kobalicek** [comment]
This would be difficult in the current codebase. I guess you will have to wait for MPSL to enable something like this. Arrays and array access is definitely planned, and would be much easier as it understands `int` type. I'm still working on the first version, but have some code that is running now.

**Comment by nelson2005** [comment]
no worries, thanks!
